-- ==============================================================================
-- BCAway Supabase Seed: Initial Known BCA Faculty & Aliases
-- (Optional to apply: run manually via Supabase SQL Editor or psql)
-- ==============================================================================

insert into public.teachers (name, aliases) values
  ('Abramson', array[]::text[]),
  ('Alschen', array[]::text[]),
  ('Barbetta', array[]::text[]),
  ('Beato', array[]::text[]),
  ('Blake', array[]::text[]),
  ('Bolton', array[]::text[]),
  ('Bonanomi', array[]::text[]),
  ('Buonocore', array[]::text[]),
  ('Calandra', array[]::text[]),
  ('Cardenas', array[]::text[]),
  ('Carter', array[]::text[]),
  ('Casarico', array[]::text[]),
  ('Coyle', array[]::text[]),
  ('Crane (Mr.)', array['Crane, Todd']::text[]),
  ('Crane (Ms.)', array['Crane, Laura']::text[]),
  ('Crimmel', array[]::text[]),
  ('Djedji', array[]::text[]),
  ('Dobrich', array[]::text[]),
  ('Dogru', array[]::text[]),
  ('Downey', array[]::text[]),
  ('Fang', array[]::text[]),
  ('Feuss', array[]::text[]),
  ('Fillebrown', array[]::text[]),
  ('Fogg', array[]::text[]),
  ('Frola', array[]::text[]),
  ('Fuentes', array[]::text[]),
  ('Gomes', array[]::text[]),
  ('Guthrie', array[]::text[]),
  ('Gutierrez', array[]::text[]),
  ('Heitzman', array[]::text[]),
  ('Hessami', array[]::text[]),
  ('Hodroski', array[]::text[]),
  ('Isecke', array[]::text[]),
  ('James', array[]::text[]),
  ('Janssen', array[]::text[]),
  ('Kaba', array[]::text[]),
  ('Kalata', array[]::text[]),
  ('Kaplan', array[]::text[]),
  ('Kim (Dr.)', array['Kim, Deok-Yang']::text[]),
  ('Kim (Mr.)', array['Kim, Jihwan']::text[]),
  ('Kim (Ms.)', array['Kim, Rosalyn']::text[]),
  ('Kramer', array[]::text[]),
  ('Lancaster', array[]::text[]),
  ('Lewitt', array[]::text[]),
  ('Loh', array[]::text[]),
  ('Lorente', array[]::text[]),
  ('MacDermott', array[]::text[]),
  ('Madden', array[]::text[]),
  ('Maks', array[]::text[]),
  ('Marmora', array[]::text[]),
  ('Mazurek', array[]::text[]),
  ('Molino', array[]::text[]),
  ('Mullally', array[]::text[]),
  ('Murano', array[]::text[]),
  ('Nodarse', array[]::text[]),
  ('Olivo', array[]::text[]),
  ('Pagano', array[]::text[]),
  ('Penev', array[]::text[]),
  ('Pero', array[]::text[]),
  ('Pinto', array[]::text[]),
  ('Pinyan', array[]::text[]),
  ('Pollinger', array[]::text[]),
  ('Ponce', array[]::text[]),
  ('Price-Halligan', array[]::text[]),
  ('Rangrez', array[]::text[]),
  ('Respass', array[]::text[]),
  ('Rhee', array[]::text[]),
  ('Rivera', array[]::text[]),
  ('Russo', array[]::text[]),
  ('Sabio', array[]::text[]),
  ('Samarakone', array[]::text[]),
  ('Sawhney', array[]::text[]),
  ('Sen', array[]::text[]),
  ('Seventko', array[]::text[]),
  ('Smith', array[]::text[]),
  ('Sorrentino', array[]::text[]),
  ('Spinelli', array[]::text[]),
  ('Symons', array[]::text[]),
  ('Torres', array[]::text[]),
  ('Villarosa', array[]::text[]),
  ('Vollenweider', array[]::text[]),
  ('Waldron', array[]::text[]),
  ('Wallace', array[]::text[]),
  ('Walsh', array[]::text[]),
  ('Wertz', array[]::text[]),
  ('Wilson', array[]::text[]),
  ('Xu', array[]::text[]),
  ('Zangara', array[]::text[]),
  ('Zhang', array[]::text[]),
  ('Zubov', array[]::text[])
on conflict (name) do update set aliases = excluded.aliases;
